import { ApiProperty } from '@nestjs/swagger';
import { IsInt, IsString } from 'class-validator';

export class TwoFactorDto {
  @ApiProperty({
    example: 1,
    description: 'User ID',
  })
  @IsInt()
  userId!: number;

  @ApiProperty({
    example: '123456',
    description: 'TOTP code generated by authenticator app',
  })
  @IsString()
  code!: string;
}
