services:
  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run start:dev
    restart: unless-stopped
